version: "3.9"

services:
  postgres:
    container_name: mc_manager_db
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - default
    environment:
      - POSTGRES_DB=mcmanager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django: &django
    container_name: mc_manager
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "2"
          memory: 6G
        reservations:
          cpus: ".1"
          memory: 256M
    depends_on:
      - postgres
    networks:
      - default
      - traefik
    volumes:
      - data:/data
    ports:
      - "25565-25600:25565-25600"
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.mc_manager.rule: Host(`minecraft.marchand.cloud`)
      traefik.http.routers.mc_manager.entrypoints: https
      traefik.http.routers.mc_manager.tls: true
      traefik.http.routers.mc_manager.tls.certresolver: letsencrypt

  django_migration:
    <<: *django
    container_name: mc_manager_migration
    deploy: {}
    command: python manage.py migrate
    volumes: []
    ports: []
    labels: {}

networks:
  default:
  traefik:
    external: true
    name: traefik

volumes:
  data:
  database:
