# Generated by Django 3.2 on 2021-04-08 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('public', models.BooleanField(default=False, verbose_name='Serveur public')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Port')),
                ('description', models.TextField(default='A minecraft server', max_length=100, verbose_name='Description')),
                ('version', models.CharField(max_length=32, verbose_name='Version')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icone')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.IntegerField(default=5, verbose_name='Maximum de joueurs')),
                ('view_distance', models.IntegerField(default=10, verbose_name='Distance de rendu (en chunck)')),
                ('level_seed', models.CharField(blank=True, max_length=128, null=True, verbose_name='Seed du monde')),
                ('gamemode', models.CharField(choices=[('survival', 'Survie'), ('creative', 'Creatif'), ('spectator', 'Spectateur'), ('adventure', 'Aventure')], default='survival', max_length=9, verbose_name='Mode de jeu')),
                ('force_gamemode', models.BooleanField(default=True, verbose_name='Forcer le gamemode')),
                ('difficulty', models.CharField(choices=[('peaceful', 'Paisible'), ('easy', 'Facile'), ('normal', 'Normale'), ('hard', 'Difficile')], default='normal', max_length=8, verbose_name='Difficulté')),
                ('level_name', models.CharField(default='world', max_length=32, verbose_name='Nom du monde')),
                ('motd', models.TextField(default='A Minecraft Server', max_length=300, verbose_name='Description du serveur')),
                ('spawn_protection', models.IntegerField(default=0, verbose_name='Protection du spawn (en block)')),
                ('hardcore', models.BooleanField(default=False, verbose_name='Hardcore')),
                ('pvp', models.BooleanField(default=True, verbose_name='PVP')),
                ('generate_structures', models.BooleanField(default=True, verbose_name='Générer des structures')),
                ('spawn_npcs', models.BooleanField(default=True, verbose_name='Villageois')),
                ('spawn_animals', models.BooleanField(default=True, verbose_name='Animaux')),
                ('spawn_monsters', models.BooleanField(default=True, verbose_name='Monstres')),
                ('enforce_whitelist', models.BooleanField(default=False, verbose_name='Activer la liste blanche')),
                ('online_mode', models.BooleanField(default=True, verbose_name='Autoriser seulement les comptes légaux')),
                ('enable_command_block', models.BooleanField(default=False, verbose_name='Activer les command blocks')),
                ('server', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.server')),
            ],
        ),
    ]
