# Generated by Django 3.2 on 2021-04-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerProperties',
        ),
    ]
