# Generated by Django 3.2 on 2021-04-16 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_delete_serverproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage', models.BooleanField(default=True, verbose_name='Démarrer / Eteindre / Paramètres de base')),
                ('properties', models.BooleanField(default=False, verbose_name='Modifier les propriétés du serveur')),
                ('administrators', models.BooleanField(default=False, verbose_name='Modifier les partages du serveur')),
                ('console', models.BooleanField(default=False, verbose_name='Accès à la console')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.server')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
