# Generated by Django 3.0.4 on 2020-05-15 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(default='A minecraft server', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='server',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Serveur public'),
        ),
        migrations.AlterField(
            model_name='server',
            name='version',
            field=models.CharField(choices=[('1.15.0', '1.15.0'), ('1.15.1', '1.15.1'), ('1.15.2', '1.15.2')], default='1.15.2', max_length=6, verbose_name='Version'),
        ),
    ]
