# Generated by Django 3.0.4 on 2020-05-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200515_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='server',
            name='version',
            field=models.CharField(choices=[('VANILLA-1.14.4.jar', 'VANILLA-1.14.4'), ('VANILLA-1.15.2.jar', 'VANILLA-1.15.2')], max_length=32, verbose_name='Version'),
        ),
    ]
