# Generated by Django 3.0.4 on 2020-05-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_serverproperties_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverproperties',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Facile'), ('normal', 'Normale'), ('hard', 'Difficile')], default='normal', max_length=6, verbose_name='Difficulté'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='enable_command_block',
            field=models.BooleanField(default=False, verbose_name='Activer les command blocks'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='enforce_whitelist',
            field=models.BooleanField(default=False, verbose_name='Activer la liste blanche'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='gamemode',
            field=models.CharField(choices=[('survival', 'Survie'), ('creative', 'Creatif'), ('spectator', 'Spectateur')], default='survival', max_length=9, verbose_name='Mode de jeu'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='generate_structures',
            field=models.BooleanField(default=True, verbose_name='Générer des structures'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='hardcore',
            field=models.BooleanField(default=False, verbose_name='Hardcore'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='level_name',
            field=models.CharField(default='world', max_length=16, verbose_name='Nom du monde'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='level_seed',
            field=models.CharField(max_length=128, verbose_name='Seed du monde'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='max_players',
            field=models.IntegerField(default=5, verbose_name='Maximum de joueurs'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='motd',
            field=models.TextField(default='A Minecraft Server', max_length=300, verbose_name='Description du serveur'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='online_mode',
            field=models.BooleanField(default=True, verbose_name='Autoriser seulement les comptes légaux'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='pvp',
            field=models.BooleanField(default=True, verbose_name='PVP'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='spawn_animals',
            field=models.BooleanField(default=True, verbose_name='Animaux'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='spawn_monsters',
            field=models.BooleanField(default=True, verbose_name='Monstres'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='spawn_npcs',
            field=models.BooleanField(default=True, verbose_name='Villageois'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='spawn_protection',
            field=models.IntegerField(default=0, verbose_name='Protection du spawn (en block)'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='view_distance',
            field=models.IntegerField(default=10, verbose_name='Distance de rendu (en chunck)'),
        ),
    ]
