# Generated by Django 3.0.4 on 2020-06-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200520_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverproperties',
            name='force_gamemode',
            field=models.BooleanField(default=True, verbose_name='Forcer le gamemode'),
        ),
        migrations.AlterField(
            model_name='serverproperties',
            name='gamemode',
            field=models.CharField(choices=[('survival', 'Survie'), ('creative', 'Creatif'), ('spectator', 'Spectateur'), ('adventure', 'Aventure')], default='survival', max_length=9, verbose_name='Mode de jeu'),
        ),
    ]
