# Generated by Django 3.0.4 on 2020-07-08 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20200603_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverproperties',
            name='level_name',
            field=models.CharField(default='world', max_length=32, verbose_name='Nom du monde'),
        ),
        migrations.CreateModel(
            name='ServerShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('full', 'Démarrage, configuration et repartage'), ('standard', 'Démarrage et configuration'), ('strict', 'Démarrage uniquement')], max_length=8, verbose_name='Type de permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='shares',
            field=models.ManyToManyField(to='main.ServerShare'),
        ),
    ]
