# Generated by Django 3.0.4 on 2020-05-15 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('public', models.BooleanField(default=False)),
                ('port', models.IntegerField()),
                ('version', models.CharField(choices=[('1.15.0', '1.15.0'), ('1.15.1', '1.15.1'), ('1.15.2', '1.15.2')], default='1.15.2', max_length=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
