# Generated by Django 3.0.4 on 2020-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200519_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_distance', models.IntegerField(default=10)),
                ('level_seed', models.CharField(max_length=128)),
                ('gamemode', models.CharField(choices=[('survival', 'Survie'), ('creative', 'Creatif'), ('spectator', 'Spectateur')], default='survival', max_length=9)),
                ('enable_command_block', models.BooleanField(default=False)),
                ('level_name', models.CharField(default='world', max_length=16)),
                ('motd', models.CharField(default='A Minecraft Server', max_length=300)),
                ('hardcore', models.BooleanField(default=False)),
                ('pvp', models.BooleanField(default=True)),
                ('spawn_npcs', models.BooleanField(default=True)),
                ('generate_structures', models.BooleanField(default=True)),
                ('spawn_animals', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('normal', 'Normale'), ('hard', 'Difficile')], default='normal', max_length=6)),
                ('spawn_monsters', models.BooleanField(default=True)),
                ('enforce_whitelist', models.BooleanField(default=False)),
                ('max_players', models.IntegerField(default=5)),
                ('spawn_protection', models.IntegerField(default=0)),
                ('online_mode', models.BooleanField(default=True)),
            ],
        ),
    ]
