# Generated by Django 3.0.4 on 2020-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200520_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverproperties',
            name='difficulty',
            field=models.CharField(choices=[('peaceful', 'Paisible'), ('easy', 'Facile'), ('normal', 'Normale'), ('hard', 'Difficile')], default='normal', max_length=8, verbose_name='Difficulté'),
        ),
    ]
