# Generated by Django 3.0.4 on 2020-05-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200520_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverproperties',
            name='level_seed',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Seed du monde'),
        ),
    ]
